---
- name: Deploy web servers
  hosts: webservers
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache HTTP server
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is running and enabled
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create a custom index.html file
      copy:
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Hello World</title>
          </head>
          <body>
              <h1>Hello World from SJSU-{{ server_id }}</h1>
          </body>
          </html>
        dest: /var/www/html/index.html
        mode: '0644'

    - name: Open port 8080 in the firewall
      ufw:
        rule: allow
       # name: 'Apache Full'
        port: 8080
        proto: tcp
