---
- name: Un-deploy web servers
  hosts: webservers
  become: yes
  vars:
    ansible_ssh_private_key_file: /Users/spartan/CMPE_272_Lab02/VM2.pem
  tasks:
    - name: Stop Apache service
      systemd:
        name: apache2
        state: stopped
    
    - name: Disable Apache service
      systemd:
        name: apache2
        enabled: no
    
    - name: Remove Apache HTTP server
      apt:
        name: apache2
        state: absent
    
    - name: Remove custom index.html file
      file:
        path: /var/www/html/index.html
        state: absent
    
    - name: Remove port 8080 from the firewall
      ufw:
        rule: deny
        name: 'Apache'
        port: '8080'
        proto: tcp

